#!/bin/bash
ssh -i ~/.ssh/infrastructure.pem ubuntu@eha.tater.io mongodump
scp -r -i ~/.ssh/infrastructure.pem ubuntu@eha.tater.io:dump/ dump/
ssh -i ~/.ssh/infrastructure.pem ubuntu@eha.tater.io "rm -rf dump/"
mongorestore --drop --port 3001 -d meteor dump/tater
rm -rf dump/
