#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )

ssh -i ~/.ssh/infrastructure.pem ubuntu@mongodb01.tater.io mongodump -d eha
scp -r -i ~/.ssh/infrastructure.pem ubuntu@mongodb01.tater.io:dump/ dump/
ssh -i ~/.ssh/infrastructure.pem ubuntu@mongodb01.tater.io "rm -rf dump/"

mongorestore --drop --port 3001 -d meteor dump/eha
rm -rf dump/
mongo localhost:3001/meteor $parent_path/resetMturk.js
